In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
i=pd.read_csv('C:\\Users\\Admin\\Desktop\\Skill Circle\\dataset\\iris.csv')
i.head(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
i['Species'].unique

<bound method Series.unique of 0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object>

In [4]:
from sklearn import preprocessing

In [5]:
label_encoder=preprocessing.LabelEncoder()

In [6]:
i['Species']=label_encoder.fit_transform(i['Species'])

In [7]:
i['Species'].unique()

array([0, 1, 2], dtype=int64)

In [8]:
X=i.iloc[:,[1,4]]
print(X)

     SepalLengthCm  PetalWidthCm
0              5.1           0.2
1              4.9           0.2
2              4.7           0.2
3              4.6           0.2
4              5.0           0.2
..             ...           ...
145            6.7           2.3
146            6.3           1.9
147            6.5           2.0
148            6.2           2.3
149            5.9           1.8

[150 rows x 2 columns]


In [9]:
Y=i.iloc[:,5].values
print(Y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


# KNN

In [10]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [11]:
X_train,x_test,Y_train,y_test=train_test_split(X,Y,test_size=1/3,random_state=0)

In [12]:
print(X_train.shape)
print(Y_train.shape)

(100, 2)
(100,)


In [13]:
print(x_test.shape)
print(y_test.shape)

(50, 2)
(50,)


In [14]:
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
x_test=sc_X.transform(x_test)

In [15]:
classifier=KNeighborsClassifier(n_neighbors=11,p=2,metric="euclidean")

In [16]:
classifier.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=11, p=2,
                     weights='uniform')

In [17]:
y_pred=classifier.predict(x_test)

In [18]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0,
       0, 1, 2, 2, 1, 2])

In [19]:
d={'test': y_test,'predict': y_pred}
dataframe=pd.DataFrame(d)
dataframe.head(10)

test  predict
0     2        2
1     1        1
2     0        0
3     2        2
4     0        0
5     2        2
6     0        0
7     1        1
8     1        1
9     1        1

In [20]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[16  0  0]
 [ 0 19  0]
 [ 0  2 13]]


In [21]:
from sklearn.metrics import accuracy_score
t=accuracy_score(y_test,y_pred)
t

0.96

# Linear Regression

In [22]:
from sklearn.linear_model import LinearRegression

In [23]:
r=LinearRegression()
r.fit(X_train,Y_train)
ypred=r.predict(x_test)

In [24]:
from sklearn.metrics import r2_score

In [25]:
r2_score(y_test,y_pred)

0.9354422207876049

# Logistic Regression

In [28]:
from sklearn.linear_model import LogisticRegression

In [30]:
log_reg=LogisticRegression()

In [33]:
log_reg.fit(X_train,Y_train)
ypred=log_reg.predict(x_test)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [39]:
cm=confusion_matrix(y_test,ypred)
print(cm)

[[16  0  0]
 [ 2 10  7]
 [ 0  1 14]]


In [40]:
from sklearn.metrics import accuracy_score
a=accuracy_score(y_test,ypred)
a

0.8

In [42]:
from sklearn.tree import DecisionTreeClassifier

In [43]:
X_train,x_test,Y_train,y_test=train_test_split(X,Y,test_size=1/3,random_state=0)

In [47]:
Dt=DecisionTreeClassifier(criterion='entropy',random_state=0)
Dt.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

In [49]:
y_pred=classifier.predict(x_test)
y_pred

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2])

In [50]:
d={'test': y_test,'predict': y_pred}
dataframe=pd.DataFrame(d)
dataframe.head(10)

test  predict
0     2        2
1     1        2
2     0        2
3     2        2
4     0        2
5     2        2
6     0        2
7     1        2
8     1        2
9     1        2

In [51]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[ 0  0 16]
 [ 0  0 19]
 [ 0  0 15]]


In [52]:
from sklearn.metrics import accuracy_score
t=accuracy_score(y_test,y_pred)
t

0.3